# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-24 13:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(blank=True, max_length=500)),
                ('Company', models.TextField(blank=True, max_length=500)),
                ('Phone', models.CharField(max_length=15)),
                ('Skype', models.CharField(blank=True, max_length=50)),
                ('Linkedin', models.CharField(blank=True, max_length=50)),
                ('Website', models.CharField(blank=True, max_length=200)),
                ('Street', models.CharField(blank=True, max_length=200)),
                ('City', models.CharField(blank=True, max_length=50)),
                ('State', models.CharField(blank=True, max_length=50)),
                ('Country', models.CharField(blank=True, max_length=200)),
                ('Title', models.CharField(blank=True, max_length=50)),
                ('BirthDate', models.DateField(null=True)),
                ('Timezone', timezone_field.fields.TimeZoneField(null=True)),
                ('Avatar', models.ImageField(upload_to='/media/images/')),
                ('Tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
