# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-30 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Avatar',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='BirthDate',
            new_name='birthDate',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Linkedin',
            new_name='linkedin',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Skype',
            new_name='skype',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='State',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Street',
            new_name='street',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Tags',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Timezone',
            new_name='timezone',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Website',
            new_name='website',
        ),
    ]
