# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-30 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editions',
            old_name='products',
            new_name='product',
        ),
    ]
